# Import Library

In [240]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets import make_blobs
import plotly
import plotly.graph_objs as go
import plotly.express as px #ใช้กับกราฟ เพิ่มสีให้กับเส้น

# สร้างโมเดล

นิยาม create_nn_model(x,y,l)function

In [241]:
def create_nn_model(x, y, l):
  input_layer = x
  weights1 = np.random.uniform(-1, 1, (input_layer.shape[1], 4))
  weights2 = np.random.uniform(-1, 1, (4, 1))
  label = y
  output_layer = np.zeros(y.shape)
  learning_rate = l

  return {'input_layer': input_layer, 'weights1': weights1, 'weights2': weights2, 'label': label, 'output_layer': output_layer, 'learning_rate': learning_rate}

สร้าง dataset เท่ากับ 3 (มิติ) และผลฌแลยเป็น 0 และ 1 จำนวน 10 records ด้วย make_blobs Function

In [242]:
x, y = make_blobs(n_samples=10, centers=2, n_features=3)
y = np.expand_dims(y, axis=1)
x.shape, y.shape

((10, 3), (10, 1))

กำหนด learning rate

In [243]:
learning_rate = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
histories = []
model = create_nn_model(x, y, learning_rate)

In [244]:
# learning_rate = 0.1
# model = create_nn_model(x, y, learning_rate)

# แสดง Model Info

แสดง shape ของ input layer

In [245]:
model['input_layer'].shape

(10, 3)

แสดง data ที่อยู่ใน input layer

In [246]:
model['input_layer']

array([[-9.10680904, -8.96405591, -2.35482279],
       [-7.40655619, -8.76645159, -3.07910043],
       [ 6.61307782, -6.97559478,  2.85121874],
       [ 6.85960168, -6.91783726,  4.24079951],
       [ 7.27569915, -5.84650365,  3.88655244],
       [-8.10371288, -9.39354906, -3.56287466],
       [ 6.82872412, -6.30457807,  4.04945142],
       [ 7.30188857, -4.98362526,  2.50304861],
       [-7.08067182, -9.74708356, -3.20490763],
       [-7.11143918, -8.70633003, -4.36421491]])

 แสดง shape ของ weights1

In [247]:
model['weights1'].shape

(3, 4)

แสดงค่าเริ่มต้นของ weights1

In [248]:
model['weights1']

array([[ 0.61503002,  0.31911557, -0.55857179,  0.8521177 ],
       [ 0.79631956,  0.9366271 , -0.18704035,  0.83431371],
       [ 0.10877305,  0.06580167,  0.58201258,  0.17382285]])

แสดง shape ของ weights2

In [249]:
model['weights2'].shape

(4, 1)

แสดงค่าเริ่มต้นของ weights2

In [250]:
model['weights2']

array([[-0.07334586],
       [ 0.89308193],
       [ 0.40343352],
       [-0.44937784]])

แสดง shape ของผลเฉลย

In [251]:
model['label'].shape

(10, 1)

แสดงค่าของผลเฉลย

In [252]:
model['label']

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0]])

แสดง shape ของ output layer

In [253]:
model['output_layer'].shape

(10, 1)

 แสดงค่าเริ่มต้นของ output layer

In [254]:
model['output_layer']

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

# นิยามและเทรนโมเดล

นิยาม sigmoid activation function และอนุพันธ์ของ sigmoid

In [255]:
def sigmoid(x):
  return 1.0/(1+ np.exp(-x))
def sigmoid_derivative(x):
  return x * (1.0 - x)

นิยาม loss function (L)

In [256]:
def loss(model):
  return sum((model['label']-model['output_layer'])**2)

นิยาม feed forward function

In [257]:
def feedforward(model):
  model['layer1'] = sigmoid(np.dot(model['input_layer'], model['weights1']))
  model['output_layer'] = sigmoid(np.dot(model['layer1'], model['weights2']))

นิยาม back propagation function เพื่อปรับค่า weights2 และ weights1

In [258]:
def backprop(model):
  d_weights2 = np.dot(model['layer1'].T, (2*(model['label']- model['output_layer']) * sigmoid_derivative(model['output_layer'])))
  d_weights1 = np.dot(model['input_layer'].T,  (np.dot(2*(model['label'] - model['output_layer']) * sigmoid_derivative(model['output_layer']), model['weights2'].T) * sigmoid_derivative(model['layer1'])))
  model['weights2'] += model['learning_rate']*d_weights2
  model['weights1'] += model['learning_rate']*d_weights1

สร้าง model แล้ว train model ในแต่ละ learning rate โดยกำหนด epoch ในการฝึกโมเดล 1000 epoch

In [259]:
for lr in learning_rate: # วนลูปผ่าน learning rates ใน list learning_rates
  model = create_nn_model(x, y, lr)  # สร้าง model ด้วย learning rate ปัจจุบัน
  history=[]  # เก็บ history ของ learning rate ปัจจุบัน

  epoch = 1000
  for i in range(epoch):
    feedforward(model)
    backprop(model)
    history.append(loss(model))

  histories.append(history)  # เพิ่ม history ของ learning rate ปัจจุบันใน list

train model กำหนด epoch ในการฝึกโมเดล 500 epoch

In [260]:
# history=[]
# epoch = 500
# for i in range(epoch):
#   feedforward(model)
#   backprop(model)
#   history.append(loss(model))

plot loss อ่านขอมูล loos จาก history ในแต่ละรอบ

In [261]:
df = pd.DataFrame(history, columns=['loss'])
df.head()

loss
0  2.280682
1  1.412792
2  1.270105
3  1.178306
4  0.574014

# Plot กราฟ

กำหนดรูปแบบ สี เส้น ชื่อแกน ชื่อเส้น จะปรากฏบนกราฟ แล้วพลอตกราฟ

In [262]:
# h1 = go.Scatter(y=df['loss'],
#                 mode="lines", line=dict(
#                 width=2,
#                 color='blue'),
#                 name="loss")
# data=[h1]

# layout1 = go.Layout(title='Loss',
#                     xaxis=dict(title='Epochs'),
#                     yaxis=dict(title=''))
# fig1 = go.Figure(data, layout=layout1)
# plotly.offline.iplot(fig1)

In [263]:
# กำหนดสีสำหรับ learning rate แต่ละตัว
colors = px.colors.qualitative.Plotly  # ใช้สีจาก Plotly

data = []  # เก็บข้อมูลสำหรับพล็อตกราฟ

for i, lr in enumerate(learning_rate):
    df = pd.DataFrame(histories[i], columns=['loss'])  # สร้าง DataFrame จาก history
    trace = go.Scatter(y=df['loss'],
                        mode="lines",
                        line=dict(width=2, color=colors[i % len(colors)]),  # กำหนดสีโดยใช้ index ของ learning rate
                        name=str(lr))  # กำหนดชื่อเส้นจาก learning rate
    data.append(trace)  # เพิ่ม trace ใน list

layout1=go.Layout(title='Loss',  # เปลี่ยนชื่อกราฟ
                  xaxis=dict(title='Epoch'),
                  yaxis=dict(title=' '))
fig1 = go.Figure(data, layout=layout1)
plotly.offline.iplot(fig1)  # พล็อตกราฟ