## **Rule การย่างเนื้อ**
*   อุณหภูมิภายในเนื้อ > 63°C คือ "สุก"
*   สีด้านในเนื้อเป็นสีชมพู คือ "สุก"
*   มีน้ำไหลออกมาจากเนื้อเมื่อกด คือ "สุก"
*   ระยะเวลาย่าง > 10 นาที คือ "สุก"
*   ย่างด้วยไฟแรง คือ "สุก"
*   พื้นผิวด้านนอกของเนื้อมีสีน้ำตาลหรือทองทอง คือ "สุก"















In [ ]:
def steak_rare_check(temperature, inner_color, juice, time, high_heat, surface_color):
  if temperature > 63:
    return True
  elif inner_color == 'pink':
    return True
  elif juice == True:
    return True
  elif time > 10:
    return True
  elif high_heat == True:
    return True
  elif surface_color == 'brown' or surface_color == 'gold':
    return True


##**Feature การย่างเนื้อ**


* อุณหภูมิภายในเนื้อ > 63°C --> True or False
* สีด้านในเนื้อเป็นสีชมพู --> True or False
* มีน้ำไหลออกมาจากเนื้อเมื่อกด --> True or False
* ระยะเวลาย่าง > 10 นาที --> True or False
* ย่างบนไฟแรง --> True or False
* พื้นผิวด้านนอกของเนื้อมีสีน้ำตาลทอง --> True or False



In [ ]:
data = [
    {"Temperature (°C)": 50, "Inner Color": "red", "Juice": False, "Time (min)": 8, "High Heat": False, "Surface Color": "red"},
    {"Temperature (°C)": 65, "Inner Color": "pink", "Juice": True, "Time (min)": 12, "High Heat": True, "Surface Color": "gold"},
    {"Temperature (°C)": 55, "Inner Color": "pink", "Juice": False, "Time (min)": 7, "High Heat": False, "Surface Color": "brown"},
    {"Temperature (°C)": 70, "Inner Color": "brown", "Juice": False, "Time (min)": 15, "High Heat": True, "Surface Color": "gold"},
    {"Temperature (°C)": 45, "Inner Color": "red", "Juice": False, "Time (min)": 5, "High Heat": False, "Surface Color": "red"},
    {"Temperature (°C)": 66, "Inner Color": "red", "Juice": True, "Time (min)": 9, "High Heat": False, "Surface Color": "gold"},
]

In [ ]:
import numpy as np

data_matrix = np.zeros((6, 6), dtype=int)

for i, item in enumerate(data):
    data_matrix[i, 0] = 1 if item["Temperature (°C)"] > 63 else 0
    data_matrix[i, 1] = 1 if item["Inner Color"] == "pink" else 0
    data_matrix[i, 2] = 1 if item["Juice"] else 0
    data_matrix[i, 3] = 1 if item["Time (min)"] > 10 else 0
    data_matrix[i, 4] = 1 if item["High Heat"] else 0
    data_matrix[i, 5] = 1 if item["Surface Color"] in ("brown", "gold") else 0

print(data_matrix)

[[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [0 1 0 0 0 1]
 [1 0 0 1 1 1]
 [0 0 0 0 0 0]
 [1 0 1 0 0 1]]


##**Features(Data)**....................**Target(Label)**
*   [0 0 0 0 0 0] .................................................. 0
*   [1 1 1 1 1 1] .................................................. 1
*   [0 1 0 0 0 1] .................................................. 0
*   [1 0 0 1 1 1] .................................................. 1
*   [0 0 0 0 0 0] .................................................. 0
*   [1 0 1 0 0 1] .................................................. 0

