In [1]:
from math import log, log2
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

import tensorflow as tf

In [2]:
p = 0.1
h = -log2(p)

print('p(x)=%.3f, information: %.3f bits' % (p, h))

p = 0.5
h = -log2(p)

print('p(x)=%.3f, information: %.3f bits' % (p, h))

p(x)=0.100, information: 3.322 bits
p(x)=0.500, information: 1.000 bits


In [3]:
probs = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
info = [-log2(p) for p in probs]

In [4]:
df = pd.DataFrame(list(zip(probs, info)), columns =['Probability', 'Information'])
df

Probability  Information
0          0.1     3.321928
1          0.2     2.321928
2          0.3     1.736966
3          0.4     1.321928
4          0.5     1.000000
5          0.6     0.736966
6          0.7     0.514573
7          0.8     0.321928
8          0.9     0.152003
9          1.0    -0.000000

In [5]:
fig = px.line(df, x='Probability', y='Information', title='Probability vs Information')
fig.show()

##Entropy

In [6]:
P = [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
entropy = -sum([p * log2(p) for p in P])
print('entropy: %.3f bits' % entropy)

entropy: 2.585 bits


In [7]:
def entropy(events, ets=1e-15):
    return -sum([p * log2(p + ets) for p in events])

probs = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
dists = [[p, 1.0 - p] for p in probs]
ents = [entropy(d) for d in dists]

In [8]:
df = pd.DataFrame(list(zip(probs, ents)), columns =['Probability Distribution', 'Entropy (bits)'])

In [9]:
fig = px.line(df, x='Probability Distribution', y='Entropy (bits)', title='Probability Distribution vs Entropy')
fig.update_xaxes(ticktext=[str(d) for d in dists], tickvals = probs)

##Cross-Entropy

In [10]:
events = ['A', 'B', 'C', 'D']
p = [1/2, 1/4, 1/8, 1/8]
q = [1/8, 1/4, 1/2, 1/8]

In [11]:
fig = go.Figure(data=[
    go.Bar(name='Probability Distribution เก่า (p)', x=events, y=p, text=p, textposition='auto'),
    go.Bar(name='Probability Distribution ใหม่ (q)', x=events, y=q, text=q, textposition='auto')
])

fig.update_layout(barmode='group')

In [12]:
def cross_entropy(p, q):
    return -sum([q[i]*log2(p[i]) for i in range(len(p))])

In [13]:
ce = cross_entropy(p, q)
print('H(P, Q): %.3f bits' % ce)

H(P, Q): 2.500 bits


##Binary Classification Loss Functions

In [14]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

data = 25
result = sigmoid(data)

print(result)

0.999999999986112


##Binary Crossentropy Loss

In [15]:
events = ['Class 0', 'Class 1']
actual = [1, 0, 1, 1, 0]
predicted = [0.7, 0.45, 0.9, 0.5, 0.3]

index = 0
p = [1-actual[index], actual[index]]
q = [1-predicted[index], predicted[index]]

In [16]:
fig = go.Figure(data=[
    go.Bar(name='Actual Probability Distribution', x=events, y=p, text=p, textposition='auto'),
    go.Bar(name='Predicted Probability Distribution', x=events, y=q, text=list(np.round(q,2)), textposition='auto')
])

fig.update_layout(barmode='group', title='Record 1')

In [17]:
index = 1
p = [1-actual[index], actual[index]]
q = [1-predicted[index], predicted[index]]

In [18]:
fig = go.Figure(data=[
    go.Bar(name='Actual Probability Distribution', x=events, y=p, text=p, textposition='auto'),
    go.Bar(name='Predicted Probability Distribution', x=events, y=q, text=q, textposition='auto')
])

fig.update_layout(barmode='group', title='Record 2')

In [19]:
index = 2
p = [1-actual[index], actual[index]]
q = [1-predicted[index], predicted[index]]

In [20]:
fig = go.Figure(data=[
    go.Bar(name='Actual Probability Distribution', x=events, y=p, text=p, textposition='auto'),
    go.Bar(name='Predicted Probability Distribution', x=events, y=q, text=np.round(q,2), textposition='auto')
])

fig.update_layout(barmode='group', title='Record 3')

In [21]:
index = 3
p = [1-actual[index], actual[index]]
q = [1-predicted[index], predicted[index]]

In [22]:
fig = go.Figure(data=[
    go.Bar(name='Actual Probability Distribution', x=events, y=p, text=p, textposition='auto'),
    go.Bar(name='Predicted Probability Distribution', x=events, y=q, text=q, textposition='auto')
])

fig.update_layout(barmode='group', title='Record 4')

In [23]:
index = 4
p = [1-actual[index], actual[index]]
q = [1-predicted[index], predicted[index]]

In [24]:
fig = go.Figure(data=[
    go.Bar(name='Actual Probability Distribution', x=events, y=p, text=p, textposition='auto'),
    go.Bar(name='Predicted Probability Distribution', x=events, y=q, text=q, textposition='auto')
])

fig.update_layout(barmode='group', title='Record 5')

In [25]:
def binary_cross_entropy_loss(actual, predicted):
    sum = 0
    for i in range(len(actual)):
        sum=sum+actual[i]*log(predicted[i])+(1-actual[i])*log(1-predicted[i])

    return -sum/len(actual)

binary_cross_entropy_loss(actual, predicted)

0.4219389169701714

In [26]:
loss = tf.keras.losses.binary_crossentropy(actual, predicted)
loss.numpy()

np.float32(0.42193896)

In [27]:
actual = [1, 0, 1, 1, 0]
predicted = [1.0, 0.0, 1.0, 1.0, 0.0]

loss = tf.keras.losses.binary_crossentropy(actual, predicted)
loss.numpy()

np.float32(1.192093e-07)

##เทรนโมเดลแบบ Binary Classification

In [28]:
to_categorical = tf.keras.utils.to_categorical
from tensorflow.keras.utils import to_categorical

import plotly
import plotly.graph_objs as go
import plotly.express as px

from sklearn.datasets import make_circles
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split

import pandas as pd

In [29]:
x, y =  make_circles(n_samples=5000, noise=0.1, random_state=1)

In [30]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.4, shuffle= True)
x_train.shape, x_val.shape, y_train.shape, y_val.shape

((3000, 2), (2000, 2), (3000,), (2000,))

In [31]:
x_train_pd = pd.DataFrame(x_train, columns=['x', 'y'])
y_train_pd = pd.DataFrame(y_train, columns=['class'], dtype='str')

df = pd.concat([x_train_pd, y_train_pd], axis=1)

In [32]:
fig = px.scatter(df, x="x", y="y", color="class")
fig.show()

In [33]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(60, input_dim=2, activation='relu', kernel_initializer='he_uniform'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



In [34]:
opt = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9)
model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

In [35]:
his = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=2000, verbose=1, batch_size = 256)

Epoch 1/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 149ms/step - accuracy: 0.5150 - loss: 0.7450 - val_accuracy: 0.4960 - val_loss: 0.7054
Epoch 2/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.5110 - loss: 0.7134 - val_accuracy: 0.5000 - val_loss: 0.6941
Epoch 3/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5142 - loss: 0.7036 - val_accuracy: 0.4975 - val_loss: 0.6850
Epoch 4/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5330 - loss: 0.6940 - val_accuracy: 0.4915 - val_loss: 0.6799
Epoch 5/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5359 - loss: 0.6885 - val_accuracy: 0.4930 - val_loss: 0.6767
Epoch 6/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5335 - loss: 0.6873 - val_accuracy: 0.5030 - val_loss: 0.6726
Epoch 7/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5379 - loss: 0.6826 - val_accuracy: 0.5125 - val_loss: 0.6689
Epoch 8/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5614 - loss: 0.6755 - val_accuracy: 

In [36]:
h1 = go.Scatter(y=his.history['loss'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='blue'),
                        name="loss"
                   )
h2 = go.Scatter(y=his.history['val_loss'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='red'),
                        name="val_loss"
                   )

data = [h1,h2]
layout1 = go.Layout(title='Loss',
                   xaxis=dict(title='epochs'),
                   yaxis=dict(title=''))
fig1 = go.Figure(data = data, layout=layout1)
plotly.offline.iplot(fig1)

In [37]:
h1 = go.Scatter(y=his.history['accuracy'],
                    mode="lines", line=dict(
                    width=2,
                    color='blue'),
                    name="acc"
                   )
h2 = go.Scatter(y=his.history['val_accuracy'],
                    mode="lines", line=dict(
                    width=2,
                    color='red'),
                    name="val_acc"
                   )

data = [h1,h2]
layout1 = go.Layout(title='Accuracy',
                   xaxis=dict(title='epochs'),
                   yaxis=dict(title=''))
fig1 = go.Figure(data = data, layout=layout1)
plotly.offline.iplot(fig1)

In [38]:
_, train_acc = model.evaluate(x_train, y_train, verbose=0)
_, val_acc = model.evaluate(x_val, y_val, verbose=0)
print('Train: %.4f, Validation: %.4f' % (train_acc, val_acc))

Train: 0.8583, Validation: 0.8315


In [39]:
res = model.predict(x_train)
print(res[:10])

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0.43183076]
 [0.7233819 ]
 [0.6772311 ]
 [0.0290338 ]
 [0.0165365 ]
 [0.39689082]
 [0.16854545]
 [0.9416037 ]
 [0.34146905]
 [0.8920098 ]]


##Multi-Class Classification Loss Functions

In [40]:
def softmax(vector):
    e = np.exp(vector)
    return e/e.sum()

data = [1, 3, 2.5]
result = softmax(data)

print(result)
print(sum(result))

[0.07769558 0.57409699 0.34820743]
1.0


In [41]:
events = ['Class 0', 'Class 1', 'Class 2']
actual = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
predicted = [[0.9, 0.05, 0.05], [0.05, 0.89, 0.06], [0.05, 0.01, 0.94]]

p = actual[0]
q = predicted[0]

In [42]:
fig = go.Figure(data=[
    go.Bar(name='Actual Probability Distribution', x=events, y=p, text=p, textposition='auto'),
    go.Bar(name='Predicted Probability Distribution', x=events, y=q, text=q, textposition='auto')
])

fig.update_layout(barmode='group', title='Record 1')

In [43]:
p = actual[1]
q = predicted[1]

fig = go.Figure(data=[
    go.Bar(name='Actual Probability Distribution', x=events, y=p, text=p, textposition='auto'),
    go.Bar(name='Predicted Probability Distribution', x=events, y=q, text=q, textposition='auto')
])

fig.update_layout(barmode='group', title='Record 2')

In [44]:
p = actual[2]
q = predicted[2]

fig = go.Figure(data=[
    go.Bar(name='Actual Probability Distribution', x=events, y=p, text=p, textposition='auto'),
    go.Bar(name='Predicted Probability Distribution', x=events, y=q, text=q, textposition='auto')
])

fig.update_layout(barmode='group', title='Record 3')

In [45]:
def categorical_cross_entropy(actual, predicted):
    sum = 0.0
    for i in range(len(actual)):
        for j in range(len(actual[i])):
            sum += actual[i][j] * log(1e-15 + predicted[i][j])
    mean = 1.0 / len(actual) * sum
    return -mean

np.around(categorical_cross_entropy(actual, predicted),5)

np.float64(0.09459)

In [46]:
cce = tf.keras.losses.CategoricalCrossentropy()
np.around(cce(actual, predicted).numpy(),5)

np.float32(0.09459)

##เทรนโมเดลแบบ Multi-Class Classification

In [47]:
x, y = make_blobs(n_samples=1000, centers=3, n_features=2, cluster_std=2, random_state=2)

In [48]:
y = to_categorical(y)
y[:10]

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [49]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.5, shuffle= True)
x_train.shape, x_val.shape, y_train.shape, y_val.shape

((500, 2), (500, 2), (500, 3), (500, 3))

In [50]:
y = np.argmax(y_train,axis=1)

x_train_pd = pd.DataFrame(x_train, columns=['x', 'y'])
y_train_pd = pd.DataFrame(y, columns=['class'], dtype='str')
df = pd.concat([x_train_pd, y_train_pd], axis=1)

In [51]:
fig = px.scatter(df, x="x", y="y", color="class")
fig.show()

In [52]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(60, input_dim=2, activation='relu', kernel_initializer='he_uniform'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(3, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



In [53]:
opt =  tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [54]:
his = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=1000, verbose=1, batch_size = 128)

Epoch 1/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 865ms/step - accuracy: 0.3144 - loss: 3.2824 - val_accuracy: 0.4600 - val_loss: 1.8656
Epoch 2/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.4337 - loss: 2.6308 - val_accuracy: 0.6660 - val_loss: 1.0735
Epoch 3/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5954 - loss: 1.5626 - val_accuracy: 0.6300 - val_loss: 1.4441
Epoch 4/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6191 - loss: 1.4090 - val_accuracy: 0.6560 - val_loss: 1.0336
Epoch 5/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6340 - loss: 1.1370 - val_accuracy: 0.6480 - val_loss: 0.9380
Epoch 6/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6055 - loss: 0.9805 - val_accuracy: 0.6160 - val_loss: 1.1064
Epoch 7/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6229 - loss: 1.1050 - val_accuracy: 0.6380 - val_loss: 1.0170
Epoch 8/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6196 - loss: 1.0927 - val_accuracy: 0.5400 - 

In [55]:
h1 = go.Scatter(y=his.history['loss'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='blue'),
                        name="loss"
                   )
h2 = go.Scatter(y=his.history['val_loss'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='red'),
                        name="val_loss"
                   )

data = [h1,h2]
layout1 = go.Layout(title='Loss',
                   xaxis=dict(title='epochs'),
                   yaxis=dict(title=''))
fig1 = go.Figure(data = data, layout=layout1)
plotly.offline.iplot(fig1)

In [56]:
h1 = go.Scatter(y=his.history['accuracy'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='blue'),
                        name="acc"
                   )
h2 = go.Scatter(y=his.history['val_accuracy'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='red'),
                        name="val_acc"
                   )

data = [h1,h2]
layout1 = go.Layout(title='Accuracy',
                   xaxis=dict(title='epochs'),
                   yaxis=dict(title=''))
fig1 = go.Figure(data = data, layout=layout1)
plotly.offline.iplot(fig1)

In [57]:
_, train_acc = model.evaluate(x_train, y_train, verbose=0)
_, val_acc = model.evaluate(x_val, y_val, verbose=0)
print('Train: %.4f, Validation: %.4f' % (train_acc, val_acc))

Train: 0.8280, Validation: 0.8120


In [58]:
res = model.predict(x_train)
print(np.round(res[:10],3))

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[[0.005 0.519 0.476]
 [0.076 0.161 0.763]
 [0.    0.696 0.304]
 [0.015 0.364 0.621]
 [0.    0.997 0.003]
 [0.    1.    0.   ]
 [0.036 0.253 0.712]
 [0.611 0.002 0.388]
 [0.011 0.413 0.576]
 [0.919 0.002 0.079]]


#Sparse Categorical Crossentropy Loss

In [59]:
x, y = make_blobs(n_samples=10000, centers=20, n_features=2, cluster_std=0.1, random_state=2)

In [60]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.5, shuffle= True)
x_train.shape, x_val.shape, y_train.shape, y_val.shape

((5000, 2), (5000, 2), (5000,), (5000,))

In [61]:
x_train_pd = pd.DataFrame(x_train, columns=['x', 'y'])
y_train_pd = pd.DataFrame(y_train, columns=['class'], dtype='str')

df = pd.concat([x_train_pd, y_train_pd], axis=1)

In [62]:
fig = px.scatter(df, x="x", y="y", color="class")
fig.show()

In [63]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(60, input_dim=2, activation='relu', kernel_initializer='he_uniform'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(20, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



In [64]:
opt = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9)
model.compile(loss='sparse_categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [65]:
his = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=1000, verbose=1, batch_size = 128)

Epoch 1/1000
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.2034 - loss: 5.3766 - val_accuracy: 0.4510 - val_loss: 1.4255
Epoch 2/1000
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4790 - loss: 1.3441 - val_accuracy: 0.5734 - val_loss: 0.8407
Epoch 3/1000
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6063 - loss: 0.9266 - val_accuracy: 0.6432 - val_loss: 0.8842
Epoch 4/1000
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6074 - loss: 0.9120 - val_accuracy: 0.6952 - val_loss: 0.7096
Epoch 5/1000
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6922 - loss: 0.7666 - val_accuracy: 0.8438 - val_loss: 0.5875
Epoch 6/1000
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7514 - loss: 0.6760 - val_accuracy: 0.8400 - val_loss: 0.5865
Epoch 7/1000
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7690 - loss: 0.6526 - val_accuracy: 0.7208 - val_loss: 0.7346
Epoch 8/1000
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7597 - loss: 0.7156 - val_accuracy: 0

In [66]:
h1 = go.Scatter(y=his.history['loss'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='blue'),
                        name="loss"
                   )
h2 = go.Scatter(y=his.history['val_loss'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='red'),
                        name="val_loss"
                   )

data = [h1,h2]
layout1 = go.Layout(title='Loss',
                   xaxis=dict(title='epochs'),
                   yaxis=dict(title=''))
fig1 = go.Figure(data = data, layout=layout1)
plotly.offline.iplot(fig1)

In [67]:
h1 = go.Scatter(y=his.history['accuracy'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='blue'),
                        name="acc"
                   )
h2 = go.Scatter(y=his.history['val_accuracy'],
                    mode="lines",
                    line=dict(
                        width=2,
                        color='red'),
                        name="val_acc"
                   )

data = [h1,h2]
layout1 = go.Layout(title='Accuracy',
                   xaxis=dict(title='epochs'),
                   yaxis=dict(title=''))
fig1 = go.Figure(data = data, layout=layout1)
plotly.offline.iplot(fig1)

In [68]:
_, train_acc = model.evaluate(x_train, y_train, verbose=0)
_, val_acc = model.evaluate(x_val, y_val, verbose=0)
print('Train: %.4f, Validation: %.4f' % (train_acc, val_acc))

Train: 0.9996, Validation: 0.9990


In [69]:
res = model.predict(x_train)
print(np.round(res[:1],3))

157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
